tarides/ocaml-platform-installer

src/distrib/make_installer.sh

It adds the same guard as the sandstorm installer but links to an archived copy of the blog post.
Closes #47

Add guard to prevent partial script from being run

---

README.md
src/bin/main.ml

This PR adds a `DETAILS` section to the man page, corresponding to a simplified version of the "Under the hood" README section. It is simplified as the man page format does not allow things such as heading level or item lists, which makes big explanation hard to read.
I also added a `SEE ALSO` section to redirect interested users to the repository, where there are more details.

Add a `DETAILS` section to the man page

---

.github/workflows/build.yaml
src/distrib/release.Dockerfile
src/distrib/release.Dockerfile.dockerignore
src/distrib/release.sh

Almost close https://github.com/tarides/ocaml-platform/issues/55 (`--version` and `--help` are fixed, the release notes remain)
A new dockerfile is needed because the image previously used for building the release didn't copy the entire repository (to speed up the tests).

Distrib: Perform 'dune subst'

---

README.md
src/distrib/make_installer.sh

We currently lack the ability to build for macos arm64 but the x86_64 should work with Rosetta.
This should be reverted as soon as we can build on macos arm.

Distribute the x86_64 binary to macos arm64 users

---

.github/workflows/build.yaml
src/bin/dune
src/bin/main.ml
src/lib/binary_package.ml
src/lib/binary_package.mli
src/lib/import.ml
src/lib/import.mli
src/lib/opam.ml
src/lib/opam.mli
src/lib/sandbox_switch.ml
src/lib/sandbox_switch.mli
src/lib/tools.ml
test/dockerfiles/Dockerfile.build
test/dockerfiles/Dockerfile.install
test/dockerfiles/Dockerfile.install-in-small-project
test/dockerfiles/Dockerfile.ocamlformat
test/dockerfiles/Dockerfile.odoc
test/dockerfiles/Dockerfile.re-install-in-small-project
test/dockerfiles/Dockerfile.reinstall_cached
test/dockerfiles/Dockerfile.reinstall_ocamlformat
test/dockerfiles/Dockerfile.small-project
test/dockerfiles/Dockerfile.version

Re-open of https://github.com/tarides/ocaml-platform/pull/52. I had to remove and re-create my Github fork after the main repository has been made public.

Avoid building the compiler in the sandbox

---

src/distrib/make_installer.sh

Remove the -x flag, which is unreadable now that the script grew.
Add logging at every important steps and more importantly, in case of a problem.
The new output is:
```
=> Download ocaml-platform-42-linux-x86_64.tar
=> Install into /usr/local/bin
Opam is not installed, installing.
=> Download opam-2.1.2-x86_64-linux
Connecting to github.com (140.82.121.4:443)
Connecting to objects.githubusercontent.com (185.199.110.133:443)
saving to 'opam'
opam                 100% |*******************************************| 7068k  0:00:00 ETA
'opam' saved
=> Install into /usr/local/bin
Installation is done. Please run 'ocaml-platform' to setup the platform.
```
When it fails while installing Opam, it shows this:
```
=> Download ocaml-platform-42-linux-x86_64.tar
=> Install into /usr/local/bin
Opam is …
```

Distrib: Improve the std outputs of the installer

---

src/lib/sandbox_switch.ml

The sandbox switch is now a local switch into a temporary directory,
which can be cleaned up more easily and can't be used concurrently.
It still shows in 'opam switch list' but it now has a weirder name.
A cleanup step is still needed, but if it fails, the switch will
eventually be removed by the system and Opam will automatically cleanup
its states.
We don't remove the reference to the sandbox switch from Opam's state
because it's still useful to know about switch that would not be cleaned
up automatically by the system.

Create the sandbox switch in a temporary directory

---

CHANGES.md
src/lib/tools.ml

The '=' operator was parsed but not handled afterward. Fix it by
simplifying the code and not using strings.
This bug is new because the problematic version constraint is new.

Fix crash while parsing version constraints

---

src/bin/main.ml

This is so all the `Fun.protect` are able to do their jobs.

Raise in case of user interruption

---

CHANGES.md
dune-project
platform.opam
src/lib/binary_package.ml
src/lib/binary_package.mli
src/lib/binary_repo.ml
src/lib/binary_repo.mli
src/lib/dune
src/lib/package.ml
src/lib/package.mli
src/lib/repo.ml
src/lib/repo.mli
src/lib/tools.ml

This PR implements @rjbou #48 suggestion of using an `install` file instead of the `install` instruction in the `opam` file.
This is good for few things:
- It is faster as `opam 2.1` do not re-scan the entire folder twice
- It is more cross-compatible as the build instruction may rely on the `cp` presence and syntax
- It install files in more logical places given the package name (see after).
The first commit of this PR is only a refactoring commit,  introducing a `Package` module. The second commit introduces the functionality.
If an installed file of a tool do not belong to any of the [installation location](https://opam.ocaml.org/doc/Manual.html#lt-pkgname-gt-install) offered by the `.install` file syntax, the tool is considered "incompatible" with `.install` file and the old build …

Use a `.install` file when possible

---

CHANGES.md
README.md
src/distrib/make_installer.sh

Fixes https://github.com/tarides/ocaml-platform-installer/issues/76
The first commit adds the `-s` flag to the curl invocation in the README. This removes the progress report, which was interfering with the sudo prompt.
The second commit uses `shasum` (which seems to be installed by default in many distros) to compute the sha512 of the downloaded archive if `sha512sum` (which isn't  available on macos) isn't installed.
I have not tested this on macos yet as I'm struggling to have a working VM.

Fix the installer on macos

---

src/bin/main.ml

Related to https://github.com/tarides/ocaml-platform-installer/issues/78
Errors during 'opam init' were inadvertently ignored.

Fix ignored error during 'opam init'

---

CHANGES.md
src/lib/ansi_box.ml

When the user interrupts by calling Ctrl+c, while the program is writing sliding logs, the result is wrong: previous logs are replaced by the sliding logs, part of the sliding logs are half removed, the prompt is in the middle of half removed logs:  
This PR fixes this by removing the `clear_logs` from the things that are executed at the end even in case of interruption:
I am not completely sure why the former behavior happened consistently (it is like `clear_logs` was running twice), and how we could achieve what was wanted before (that the sliding logs are removed in case of user interruption), but I think it is good to keep the sliding logs in case of user interruption.

Small fix for wrong behaviour when user interrupts sliding logs

---

CHANGES.md
src/lib/binary_package.ml
src/lib/package.ml
src/lib/package.mli

The `available` field is filled with the `arch` condition and the `os-distribution` condition. This can be useful for the remote repo CI.
In any case, we might create one remote repo per (arch, os-distribution), and add only the repo we need, but it won't harm to have the `available` field additional check.

Add an `available` field to the repo.

---

CHANGES.md
README.md
src/lib/ansi_box.ml
src/lib/opam.ml

The error message in case of missing dependency in ocaml-platform is not explicit at all:
For instance, if `patch` and `unzip` are missing, here would be the outputs:
In non verbose and verbose:
```
root@9acca02b34cb:/# ocaml-platform 
ocaml-platform: [ERROR] Command 'opam init --yes -q --color=never --root /root/.opam' failed: exited with 50
root@9acca02b34cb:/# ocaml-platform -v
ocaml-platform: [ERROR] Command 'opam init --yes -q --color=never --root /root/.opam' failed: exited with 50
```
and in very verbose mode
```
root@6906f5bf3e4a:/# ocaml-platform -vv
ocaml-platform: [DEBUG] Running: 'opam' 'init' '--yes' '-q' '--color=never' '--root' '/root/.opam'
ocaml-platform: [DEBUG] Error in execution:   - unzip
- patch
[ERROR] Missing dependencies -- the following commands are required for …
```

Fixing errors logging, Adding dependencies and link to Up and Running to the README

---

.github/workflows/build.yaml
CHANGES.md
src/lib/binary_repo/binary_package.ml
src/lib/binary_repo/binary_package.mli
src/lib/binary_repo/binary_repo.ml
src/lib/binary_repo/dune
src/lib/binary_repo/package.ml
src/lib/binary_repo/package.mli
src/lib/binary_repo/repo.ml
src/lib/binary_repo/repo.mli
src/lib/installed_repo.ml
src/lib/opam.ml
src/lib/opam.mli
src/lib/sandbox_compiler_package.ml
src/lib/sandbox_compiler_package.mli
src/lib/sandbox_switch.ml
src/lib/sandbox_switch.mli
src/lib/tools.ml
test/dockerfiles/Dockerfile.ocaml5
test/tests/ocaml5.sh
test/tests/switch-5.0.sh

In this PR, we fix the issue that only compiler version that have a corresponding `ocaml-system` could be installed.
We fix this by creating (yet another) local repo with custom `ocaml-system` and `ocaml` packages, that the sandbox switch will use to "install" its compiler.
This makes the installer support OCaml 5 :smile: as well as other variants.
Pairprogrammed with @Julow and based on #82.

Allow for ocaml version that do not have an `ocaml-system` corresponding package (AKA OCaml 5 support!)

---

src/bin/main.ml

The installation of `utop` is not managed by `ocaml-platform`. It should not be mentioned in the `--help` page!

Remove mention of `utop` in the `--help` page

---

CHANGES.md

We forgot to update the changelog file when cutting the 0.2.0 release, which was intended for beta-testers.

Update changelog for 0.2.0

---

.github/workflows/build.yaml

They take 5 hours and are not especially needed.

Disable tests for non-x86_64

---

CHANGES.md
src/lib/tools.ml

Currently, if a tool is not compatible with the selected compiler, an
uncaught exception happens and the process is killed.
To avoid this, incompatible tools are logged and the installer is
allowed to continue with the other tools in the list.
Missing tools are also printed again at the end for clarity.
For example, `ocaml-lsp-server` is not compatible with `ocaml.5.0.0~alpha0`:
```
* Inferring tools version...
-> dune will be installed as dune.3.3.1-ocaml5.0.0~alpha0
-> dune-release will be installed as dune-release+bin+platform.1.6.2-ocaml5.0.0~alpha0
-> merlin will be installed as merlin+bin+platform.4.4.1~5.0preview-ocaml5.0.0~alpha0
ocaml-platform: internal error, uncaught exception:
Not_found
```
The output now looks like this:
```
* Inferring tools version...
-> dune will be …
```

Continue installing if a tool is not available

---

CHANGES.md
src/lib/opam.ml

The `opam` cli is versioned. We want to support opam 2.0 and therefore have to define an `OPAMCLI` environment variable, ignored by opam 2.0, and making opam>2.0 use the opam 2.0 cli.
This environment variable is added to `opam_opts`'s environment as it is only the `Opam` module which can decide which version to use.
Previous
```
ser@d6ed97d05644:~$ ocaml-platform -vv
ocaml-platform: [DEBUG] Running: 'opam' 'config' 'var' 'ocaml:compiler' '--yes' '-q' '--color=never' '--root' '/home/user/.opam'
ocaml-platform: [INFO] Error in 'opam' 'config' 'var' 'ocaml:compiler' '--yes' '-q' '--color=never' '--root' '/home/user/.opam':
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
ocaml-platform: [DEBUG] Running: 'opam' …
```

Use the `OPAMCLI` env var to fix the CLI version to "2.0"

---

CHANGES.md
src/lib/opam.ml
src/lib/tools.ml

It's a good practice to avoid blocking for several minutes without any logging.

Log before initialising Opam

---

dune-project
platform.opam

The CI reported build failures with OCaml 4.10.0 but instead of fixing them, I suggest supporting only the more recent versions.
This project is not meant to be built inside an Opam switch, which means that we can have more freedom in our dependencies without thinking about compatibility with other tools.

Constraint OCaml >= 4.10.0

---

src/distrib/make_installer.sh

The arguments of the command need to be separated by two spaces.
See https://issuecloser.com/blog/add-extra-space-between-shasum-args for an explanation:
> When checking, the input should be a former output of this program. The default mode is to print a line with checksum, a character indicating type (*' for binary, ' for text, U' for UNIVERSAL,^' for BITS, `?' for portable), and name for each FILE.
> 
> So the first space denotes the text type, and the second space separates the sum+type from the filename.
cc @samoht, thanks for the report!

Fix usage of `shasum` command

---

CHANGES.md
src/lib/tools.ml

With a mix of situation:
```
user@fc1c861174f2:~$ ocaml-platform 
* Inferring tools version...
-> dune is already installed
-> dune-release.1.6.2 will be installed from cache
-> merlin.3.8.0 will be installed from cache
-> ocaml-lsp-server is already installed
-> odoc.2.1.1 will be built from source
-> ocamlformat.0.24.1 will be installed from cache
* Building the tools...
-> Creating a sandbox...
-> [1/1] Building odoc...
* Installing tools...
-> The tools have been installed. For more information on the platform tools, run `ocaml-platform --help`
* Success.
```
The main differences are:
- There is a mention whether it is "built from source" or "installed from cache"
- The version is given instead of the (somehow internal) binary package name. The `+bin+platform` explanation can still be …

Improving logging

---

src/distrib/make_installer.sh

Currently, we hardcode in the installer script the version of the opam binary to install.
Although I think this should change, as a quick patch, this PR bumps this hardcoded version from 2.1.2 to 2.1.3.

Install opam 2.1.3 in the installer script

---

CHANGES.md
src/lib/opam.ml
src/lib/opam.mli
src/lib/sandbox_compiler_package.ml
src/lib/sandbox_compiler_package.mli
src/lib/sandbox_switch.ml
src/lib/tools.ml

This replace #105.
- We only use the cache in the following case: the compiler package is one of the standard ones (`ocaml-base-compiler`, `ocaml-system` and `ocaml-variants`), and it is unpinned.
- We use the unsuffixed version for the `ocaml-system` sandbox switch package, and disable version check (anyway, there is an uncertainty to me on what will be the value of `Sys.ocaml_version`: on `ocaml-variants.4.14.0~rc2+options` it is `4.14.0~rc2`, while the [doc](https://v2.ocaml.org/api/Sys.html#VALocaml_version) of `Sys.ocaml_version` says that `+` suffixes can be outputted).
- Using the unsuffixed `ocaml-system` package version allows us to avoid patching the `ocaml` package, simplifying the code a lot. Anyway, the package contents did not depends on the suffixes...
- Note that if we …

Support all compilers, caching only unpinned standard ones

---

.github/workflows/build.yaml
CHANGES.md
src/lib/binary_repo/binary_package.ml
src/lib/binary_repo/binary_package.mli
src/lib/binary_repo/package.ml
src/lib/binary_repo/package.mli
src/lib/tools.ml
test/dockerfiles/Dockerfile.version_dependent
test/tests/version_dependent.sh

Some tools are not sensitive to ocaml version (currently, `ocamlformat` and `dune-release`). However, they were built once per ocaml version in the cache. This commit makes a difference between those two types of tools, and for the insensitive ones, do not depend on the ocaml version.
This makes a very clear speed boost, especially for packages that are long to install (e.g. `ocamlformat`) and opens the possibility to add more (as in #107) without too much speed lost.

Do not distinguish between ocaml version in cache when unnecessary

---

.github/workflows/build.yaml
CHANGES.md
src/lib/tools.ml
test/dockerfiles/Dockerfile.install
test/dockerfiles/Dockerfile.install-in-small-project
test/dockerfiles/Dockerfile.pinned-compiler
test/dockerfiles/Dockerfile.small-project
test/tests/check_cache_is_empty.sh
test/tests/install-in-small-project.sh
test/tests/ocamlformat.sh
test/tests/odoc.sh
test/tests/pin-ocaml-compiler.sh
test/tests/re-install-in-small-project.sh
test/tests/small-project.sh

Tools built on a pinned compilers need to be stored on a repository in order to be installed back in the user's switch. The cache repository was used for this, which contradicts the restriction that the cache isn't used with pinned compiler and might be unsafe.
Use a new temporary repository to make sure that these packages don't leak into the global cache. It is created on the fly and removed when it's no longer needed.
Packages that don't depend on the version of OCaml are no longer pulled from the cache in this case.
This could be added back with more code and more bugs. What do you think ?

Use a temporary cache repo in case of pinned compiler

---

CHANGES.md
src/lib/binary_repo/binary_repo.ml
src/lib/binary_repo/binary_repo.mli
src/lib/tools.ml
test/tests/check_cache_is_empty.sh

Fix "regression" introduced in #115.
We need to verify that the packages are taken first from `dependent_repo` and then from `independent_repo`.

Use cache for packages independent from ocaml version

---

CHANGES.md
README.md

Update the fact that it is in alpha and not just a work in progress.
Fix the fact that `macos/arm64` is supported, and remove the Rosetta mention (on the contrary, it should not be used!)

Fix changelog 0.6.0

---

.github/workflows/build.yaml
CHANGES.md
src/lib/opam.ml
src/lib/opam.mli
src/lib/tools.ml
test/dockerfiles/Dockerfile.ocamlformat_user_installed
test/tests/ocamlformat_user_installed.sh

Fix https://github.com/tarides/ocaml-platform-installer/issues/126
Installing a tool was skipped if it was already installed on the current switch, regardless of its required version.
This only affected ocamlformat.
I moved some code for readability, which was being re-indented anyway.

Don't skip installing if the installed version does not satisfy the request

---

.github/workflows/build.yaml
CHANGES.md
src/lib/tools.ml
test/dockerfiles/Dockerfile.continue-when-build-fails
test/tests/failing_ocamlformat.sh

Fixes #132 
Currently, it still ends with an error, but the error message is a bit misleading without the context... Here is an output when the build of ocamlformat fails (the settings of the test):
```
opam@27c407da8c89:~/helloworld$ ocaml-platform
* Inferring tools version...                                                                                        
-> dune is already installed
-> dune-release.1.6.2 will be installed from cache
-> merlin.4.6-413 will be installed from cache
-> ocaml-lsp-server.1.10.5 will be installed from cache
-> odoc.2.1.1 will be installed from cache
-> ocamlformat.0.24.1 will be built from source
* Building the tools...
-> Creating a sandbox...
-> [1/1] Building ocamlformat...
ocaml-platform: [WARNING] There was an error during build of ocamlformat. …
```

Continue the process even if the build of a tool failed.

---

CHANGES.md
src/lib/import.ml
src/lib/import.mli
src/lib/opam.ml
src/lib/opam.mli
src/lib/sandbox_compiler_package.ml
src/lib/sandbox_compiler_package.mli
src/lib/sandbox_switch.ml

Might fix https://github.com/tarides/ocaml-platform-installer/issues/130
These packages are only needed while building in the sandbox switch and are not costly to re-create every time. This eliminate bugs due to outdated persisted data.
'Sandbox_compiler_package' is rewritten in the "with_resource" style to accomodate the new 'with_sandbox_compiler_repo' function. This remove the tedious 'deinit' code and the need to add more book keeping for the new temporary directory.

Don't persist sandbox compiler packages

---

CHANGES.md
src/lib/cache.ml
src/lib/cache.mli
src/lib/installed_repo.ml
src/lib/installed_repo.mli
src/lib/opam.ml
src/lib/opam.mli
src/lib/tools.ml
test/tests/pin-ocaml-compiler.sh

Implements #139 by putting the cache repository in `<switch-prefix>/var/cache/ocaml-platform`.

Keep the cache repository enabled

---

.github/workflows/build.yaml
CHANGES.md
src/lib/cache.ml
test/dockerfiles/Dockerfile.migrate_01

Rebased on top of both https://github.com/tarides/ocaml-platform-installer/pull/135 and https://github.com/tarides/ocaml-platform-installer/pull/136 (must be rebased and merged last)
Fix https://github.com/tarides/ocaml-platform-installer/issues/131
This adds a mechanism to migrate the cache after the tool is upgraded. The cache has an incrementing version number written to it, which is checked before doing anything with it.
TODO:

Cache migration

---

src/lib/binary_repo/repo.ml

The sandboxed compiler packages repository is created in a temporary directory. Only whether the target directory exists was checked before skipping initialisation.
Initialisation was skipped, which Opam was complaining about.

Properly init the sandbox compiler packages repo

---

CHANGES.md
src/distrib/make_installer.sh

Fix https://github.com/tarides/ocaml-platform-installer/issues/141
Install the binary into `/usr/local/bin` only if it exists, otherwise install into `/usr/bin`.
The current 'install' command would install the platform binary as `/usr/local/bin` literally, which is highly unwanted.

Avoid installing to /usr/local if it doesn't exist

---

.github/workflows/build.yaml

`--version` is returning the commit hash because the checkout step in CI is not fetching the tags.
According to the [doc](https://github.com/actions/checkout):
> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags. Refer here to learn which commit $GITHUB_SHA points to for different events.

Fix --version not returning the version

---

CHANGES.md
src/lib/sandbox_compiler_package.ml
src/lib/sandbox_switch.ml

This PR makes sandbox repos as short-lived as possible (there is no need to keep them as soon as the compiler has been installed) and give them unique name depending on the path (adding a repo to opam, with an already existing name but a different path, makes it fail).
Should hopefully make #149 never happen again.

Uniquely named and short-lived compiler sandbox repo

---

.github/workflows/build.yaml
CHANGES.md
src/lib/binary_repo/binary_package.ml
src/lib/cache.ml
test/dockerfiles/Dockerfile.migrate_from_0
test/dockerfiles/Dockerfile.migrate_from_1

I don't know if we should introduce a new version for the cache: the packages ocamlformat and merlin are incomplete as not all files are installed... But the only migration I see would be to remove those packages from the cache.

Fix `share` folder not being installed completely
